### ISSUE TITLE
Understanding Problem? (R39)

### ISSUE THREAD

**Issue by andig91** [DieBieEngineering/DieBieMS#2]
Hello!

The last days I have seen your BMS.
Fully interested I have looked at the scematic.

Is there anywhere a description of the different parts or can you answer me few questions?

Now one question. For what is R39, its look like shorting the cell.
Should it a solder brigde? It isn't in BOM.
I don't have enough experience in altium for "understanding the whole schematic".

When you say BMS from 6S to 12S.
When I am connection different series of packs need i have to solder R39 on unused cells?
Or is this only software config?

Why is 6S the minimum?
Or isn't it? Only 12V?

I hope you can help me.
Thank you a lot.
Regards
Andy

<img width="389" alt="2018-10-03 07_07_51-diebiems_db10005_diebiems pdf at master diebieengineering_diebiems github" src="https://user-images.githubusercontent.com/43803844/46391227-009a0a00-c6dc-11e8-9e51-c63c4fea3974.png">

**Comment by DieBieEngineering** [comment]
Hi! 

Sorry no description or manual yet, due to the hierarchical schematic build it should be relatively ok to read / understand. 

R39 is an option to bypass a cell measure an balance input. When for example using the bms with a 8S battery you should according to the LTC6803 specification short the unused cell inputs (in the 8S case the top 4 cell inputs), this can be done with R39 (there are 12 instances of the cell balance schematic you posted with all "jumper" / bypass 0R resistors called R39 ). 

In the PCB production output files and the production variant the R39 is stated as non populated. 

The 6S to 12S states the "usable" range (where the currents are normally acceptable), It can operate from 4S to 12S but the low / empty battery voltage tends to get really low for the power supply to operate. If I remember correctly there is also a minimal voltage requirement for the LTC.

So far in 95% of all application I never populate R39, the BMS and thus LTC performs just fine with the inputs open.
